### PR TITLE
QOL Updates

### PR DESCRIPTION
**Pull request by TheRealFlyingCoder**
Hey hey,

Just updating all the remix oAuth packages to include a typed scope array option for easier use, along with some other QOL things to help when I update remix-auth-socials :)

### CODE REVIEW

**Comment by juhanakristian** [comment]
Thanks @TheRealFlyingCoder

**Comment by TheRealFlyingCoder** [comment]
Hey @juhanakristian  just waiting on a bump and publish for this I can see the linter failures.

To be honest for this single package i'd just drop the linter rather than work through the weird unicorn issues... The eslint config you have is a bit overkill

**Comment by juhanakristian** [comment]
Hi, @TheRealFlyingCoder I resolved the linter failures and published a new version. There were some breaking changes introduced with an earlier PR #7 so the latest version is 2.0.0. Thanks again for your contributions 👍

**Comment by TheRealFlyingCoder** [comment]
> Hi, @TheRealFlyingCoder I resolved the linter failures and published a new version. There were some breaking changes introduced with an earlier PR #7 so the latest version is 2.0.0. Thanks again for your contributions 👍

Legend thanks!

**Pull request merged**
